function Hd = Lowpass_10_FIR_Equiriple
%LOWPASS_10_FIR_EQUIRIPLE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 17-Mar-2015 14:22:28

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 20;  % Sampling Frequency

Fpass = 9;               % Passband Frequency
Fstop = 9.8;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
