diary 'par_output.txt';
diary on;
nikCell_t = andro_js_t_normalized; nikCell = andro_js; Fs = 20;
par;
% pause;
nikCell_t = i4_js_t_normalized; nikCell = i4_js; Fs = 20;
par;
% pause;
nikCell_t = i4s_js_t_normalized; nikCell = i4s_js; Fs = 60;
par;
% pause;
nikCell_t = i6_js_t_normalized; nikCell = i6_js; Fs = 60;
par;
% pause;
nikCell_t = andro_ntv_t_normalized; nikCell = andro_ntv; Fs = 100;
par;
% pause;
nikCell_t = i4_ntv_t_normalized; nikCell = i4_ntv; Fs = 100;
par;
% pause;
nikCell_t = i4s_ntv_t_normalized; nikCell = i4s_ntv; Fs = 100;
par;
% pause;
nikCell_t = table_t; nikCell = table; Fs = 800;
par;
% pause;